version: '3'

services:

  app:
    build: .
    volumes:
      - .:/go/src/
      #- /Users/walterdis/go/src/fullcycle-video-encoder:/go/src
    ports:
      - "8081:8081"
    networks:
      - go-fc-challenge


networks:
  go-fc-challenge:
    driver: bridge